# Generated by Django 3.1.2 on 2021-06-10 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_roles', '0003_auto_20210603_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(upload_to='images/tourist')),
                ('passport_number', models.BigIntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guide_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.ImageField(upload_to='images/guide')),
                ('citizenship_number', models.BigIntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
