# Generated by Django 3.1.2 on 2021-06-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_roles', '0004_guide_profile_tourist_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide_profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
