# Generated by Django 3.1.2 on 2021-06-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_roles', '0005_auto_20210610_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='images/destinations')),
            ],
        ),
        migrations.RenameField(
            model_name='tourist_profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
