# Generated by Django 3.1.2 on 2021-06-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_roles', '0006_auto_20210611_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
